inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails

Layout/LineLength:
  Enabled: true
  Max: 80

Style/GuardClause:
  MinBodyLength: 2

Metrics/MethodLength:
  Max: 15

Style/FrozenStringLiteralComment:
  Enabled: false
